### ISSUE TITLE
Medium Severity Vulnerability

### ISSUE THREAD

**Issue by Doges** [acostes/deezer-node-api#3]
The package got an outdated dependency which is vulnerable and can affect users, its the request, which got the another dependency which is the tunnel-agent, please update the package to fix the vulnerability.

Thanks.

**Comment by acostes** [comment]
Hello,

Thanks for the notice. I publish a new version with the updated packages. https://github.com/acostes/deezer-node-api/commit/db9cc6ec5eb54c6ca2aea8b99caa88f3aca8c2ac
